// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJDpezDnKo3d7eLxci7w-YqzIVRHqOVzA',
    appId: '1:971113771930:web:828209258d50c9e6364023',
    messagingSenderId: '971113771930',
    projectId: 'todo--app-23f28',
    authDomain: 'todo--app-23f28.firebaseapp.com',
    storageBucket: 'todo--app-23f28.firebasestorage.app',
    measurementId: 'G-1NDLKN75PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMy9d2kD6nexX2tbdMoYbsI1of5LK4QkA',
    appId: '1:971113771930:android:1524616972e37f66364023',
    messagingSenderId: '971113771930',
    projectId: 'todo--app-23f28',
    storageBucket: 'todo--app-23f28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoQ4ltgAWmCuBVZ6G3xpUNnkG0gMyj34o',
    appId: '1:971113771930:ios:70509dead34da739364023',
    messagingSenderId: '971113771930',
    projectId: 'todo--app-23f28',
    storageBucket: 'todo--app-23f28.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoQ4ltgAWmCuBVZ6G3xpUNnkG0gMyj34o',
    appId: '1:971113771930:ios:70509dead34da739364023',
    messagingSenderId: '971113771930',
    projectId: 'todo--app-23f28',
    storageBucket: 'todo--app-23f28.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJDpezDnKo3d7eLxci7w-YqzIVRHqOVzA',
    appId: '1:971113771930:web:fded3fe95751b7b8364023',
    messagingSenderId: '971113771930',
    projectId: 'todo--app-23f28',
    authDomain: 'todo--app-23f28.firebaseapp.com',
    storageBucket: 'todo--app-23f28.firebasestorage.app',
    measurementId: 'G-KGGJD7ZSGE',
  );
}
